### ISSUE TITLE
Pressing ALT+Enter to go into full screen crashes the PlayKey Streaming Window

### ISSUE THREAD

**Issue by terric** [vilkoz/playkey-linux-launcher#3]
When using PlayKey to stream a game, on the bottom it says that you can press ALT+Enter to go into full screen. However, doing this crashes the window and requires the user to restart PlayKey.

Workaround:  
I could resize the Window to fit most of my screen (on Arch Linux with XFCE Desktop Environment).

Possible Fixes:  
Maybe the full screen feature could work by installing some additional winetricks package or a different version of wine?

**Comment by vilkoz** [comment]
Could you provide the exact error that occurs when you press ALT+Enter?
I got the following error from X server:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  215
  Current serial number in output stream:  235
```

**Comment by terric** [comment]
Here's what my terminal says, when it crashes:
```
failed to create drawable
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  223
  Current serial number in output stream:  243
X Error of failed request:  GLXBadWindow
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  32 (X_GLXDestroyWindow)
  Serial number of failed request:  5239
  Current serial number in output stream:  5239
```

**Comment by vilkoz** [comment]
On my laptop I get the same error from X server, but on desktop no error occurs and everything works fine.
I use wine-4.11 on both systems, so wine version shouldn't cause that problem.
Also, additional winetricks library shouldn't help, because playkey-linux uses clean wine prefix with no libraries in ~/.playkey-linux/wine_prefix on my desktop - and ALT-Enter still works on desktop.
I've tried to run playkey-linux in the virtual machine and for clean Manjaro and Arch Linux - everything works fine.
BTW, on virtual machines I've got `xorg-server 1.20.5-1` installed, as well as on desktop, but on the laptop where full screen mode doesn't work `xorg-server 1.20.5-2` is installed.

**Comment by terric** [comment]
Sounds like that could be it. When I have some time to fiddle around, I'll try that and see if it does the trick...

**Comment by vilkoz** [comment]
Updating the `xorg-server` package in VM to version `1.20.5-2` didn't break the fullscreen feature.

As I found the `BadMatch` error could be caused by problems with graphics drivers.

So, to recap: 

|  | Arch Linux Laptop | Manjaro Desktop | Manjaro VM | Arch Linux VM |
| -- | -- | -- | -- | -- |
| Wine Version | 4.11 | 4.11 | 4.11 | 4.11 |
| Winetrics libs | none | none | none | none |
| xorg-server version | 1.20.5-2 | 1.20.5-1 | 1.20.5-1 | 1.20.5-2 |
| Graphics driver | xf86-video-intel 1:2.99.917 | nvidia 430:26-0 | xf86-video-vesa 2.4.0-2 | video-vmware 2017.03.21 |
| Fullscreen works | No | Yes | Yes | Yes |

**Comment by vilkoz** [comment]
I've some progress with running Playkey Launcher in the fullscreen mode by rendering playkey-linux via nvidia discrete gpu using `optirun`.

Also, I've previously tried to launch playkey-linux in the wm started with `nvidia-xrun`, but got the same error.

It seems that the only way to run Playkey Launcher in fullscreen on Nvidia Optimus laptop is to run it via bumblebee with command `optirun playkey-linux`.

**Comment by terric** [comment]
I am also using an Nvidia laptop with Bumblebee etc. and using `optirun playkey-linux` makes it possible to go into full screen without crashing.

So now everything works without any problems. Awesome work with this!
