### ISSUE TITLE
DxVideoDecoder errors: IDirect3DDeviceManager9::GetVideoService() FAILED

### ISSUE THREAD

**Issue by DreadPirateSergey** [vilkoz/playkey-linux-launcher#6]
Hi, i have this erros when trying to start playkey client.
I tried to start it under i3 and Gnome, and also tried last version of Wine and Wine Staging
Can you give me your contact(messanger or someting)?
![image](https://user-images.githubusercontent.com/35541456/83732512-5fb0de80-a676-11ea-84d0-e787cc2b6997.png)

**Comment by vilkoz** [comment]
Hello, I think the described issue is not related to the playkey-launcher itself.

In `dxva2api.h` the `0x80041002L` value means DXVA2_E_VIDEO_DEVICE_LOCKED, as you can see on screenshot:
![image](https://user-images.githubusercontent.com/16705559/83735451-17cf8e80-a659-11ea-86dc-8604ec4fd049.png)

In [win32 dxva2api docs](https://docs.microsoft.com/en-us/windows/win32/api/dxva2api/nf-dxva2api-idirect3ddevicemanager9-getvideoservice) I don't see that the function `GetVideoService()` can return this value, but it may be implementation dependent.
So, in general, I would say that the output DXVA2_E_VIDEO_DEVICE_LOCKED signalize about one of:
* improper video device setup (e.g. unsatisfied dependency on `libva` or something)
* lack of video decoding drivers 
* lack of userspace libraries for 32bit apps (e.g. lib32-mesa for intel on Arch Linux)
* lack of dxva or dx3d libraries in wine prefix

I won't support this issue, because it is not related to the launcher. Try running other applications that require video decoding if you want to confirm that the root cause of your issue lays in the configuration of your system.
You should ask for support at Linux community in Telegram (e.g. https://t.me/archlinux_ru https://t.me/archlinuxgroup or one suitable for your distribution)
